import "../assets/styles/nullable.css";
import "../assets/styles/index.scss";
import localFont from "next/font/local";
import type { Metadata } from "next";
import Header from "../components/global/Header";
import Footer from "../components/global/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Montserrat = localFont({
  src: [
    {
      path: "../assets/fonts/Montserrat/Semibold/Montserrat.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/Montserrat/Medium/Montserrat.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/Montserrat/Regular/Montserrat.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  preload: true,
  display: "swap",
});

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return (
    <html className={Montserrat.className} lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout